//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLD.Web.ComunService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogError", Namespace="http://schemas.datacontract.org/2004/07/PLD.BusinessEntities.Comun")]
    [System.SerializableAttribute()]
    public partial class LogError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime datFechaErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchHostNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchIPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchMensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchParametrosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchStakeTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime datFechaError {
            get {
                return this.datFechaErrorField;
            }
            set {
                if ((this.datFechaErrorField.Equals(value) != true)) {
                    this.datFechaErrorField = value;
                    this.RaisePropertyChanged("datFechaError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchHostName {
            get {
                return this.vchHostNameField;
            }
            set {
                if ((object.ReferenceEquals(this.vchHostNameField, value) != true)) {
                    this.vchHostNameField = value;
                    this.RaisePropertyChanged("vchHostName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchIP {
            get {
                return this.vchIPField;
            }
            set {
                if ((object.ReferenceEquals(this.vchIPField, value) != true)) {
                    this.vchIPField = value;
                    this.RaisePropertyChanged("vchIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchMensaje {
            get {
                return this.vchMensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.vchMensajeField, value) != true)) {
                    this.vchMensajeField = value;
                    this.RaisePropertyChanged("vchMensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchParametros {
            get {
                return this.vchParametrosField;
            }
            set {
                if ((object.ReferenceEquals(this.vchParametrosField, value) != true)) {
                    this.vchParametrosField = value;
                    this.RaisePropertyChanged("vchParametros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchStakeTrace {
            get {
                return this.vchStakeTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.vchStakeTraceField, value) != true)) {
                    this.vchStakeTraceField = value;
                    this.RaisePropertyChanged("vchStakeTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchUsuario {
            get {
                return this.vchUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.vchUsuarioField, value) != true)) {
                    this.vchUsuarioField = value;
                    this.RaisePropertyChanged("vchUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResult", Namespace="http://schemas.datacontract.org/2004/07/PLD.BusinessEntities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PLD.Web.ComunService.Carga[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PLD.Web.ComunService.Carga))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PLD.Web.ComunService.LogError))]
    public partial class ServiceResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ResultValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ServiceOkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object ResultValue {
            get {
                return this.ResultValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultValueField, value) != true)) {
                    this.ResultValueField = value;
                    this.RaisePropertyChanged("ResultValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ServiceOk {
            get {
                return this.ServiceOkField;
            }
            set {
                if ((this.ServiceOkField.Equals(value) != true)) {
                    this.ServiceOkField = value;
                    this.RaisePropertyChanged("ServiceOk");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Carga", Namespace="http://schemas.datacontract.org/2004/07/PLD.BussinesEntities.Comun")]
    [System.SerializableAttribute()]
    public partial class Carga : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intLogIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> sdatFechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> sintNoErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> sintNoExitoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchParametrosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchXMLErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intLogID {
            get {
                return this.intLogIDField;
            }
            set {
                if ((this.intLogIDField.Equals(value) != true)) {
                    this.intLogIDField = value;
                    this.RaisePropertyChanged("intLogID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> sdatFecha {
            get {
                return this.sdatFechaField;
            }
            set {
                if ((this.sdatFechaField.Equals(value) != true)) {
                    this.sdatFechaField = value;
                    this.RaisePropertyChanged("sdatFecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> sintNoError {
            get {
                return this.sintNoErrorField;
            }
            set {
                if ((this.sintNoErrorField.Equals(value) != true)) {
                    this.sintNoErrorField = value;
                    this.RaisePropertyChanged("sintNoError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> sintNoExito {
            get {
                return this.sintNoExitoField;
            }
            set {
                if ((this.sintNoExitoField.Equals(value) != true)) {
                    this.sintNoExitoField = value;
                    this.RaisePropertyChanged("sintNoExito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchDescripcion {
            get {
                return this.vchDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.vchDescripcionField, value) != true)) {
                    this.vchDescripcionField = value;
                    this.RaisePropertyChanged("vchDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchParametros {
            get {
                return this.vchParametrosField;
            }
            set {
                if ((object.ReferenceEquals(this.vchParametrosField, value) != true)) {
                    this.vchParametrosField = value;
                    this.RaisePropertyChanged("vchParametros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchUsuario {
            get {
                return this.vchUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.vchUsuarioField, value) != true)) {
                    this.vchUsuarioField = value;
                    this.RaisePropertyChanged("vchUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchXMLError {
            get {
                return this.vchXMLErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.vchXMLErrorField, value) != true)) {
                    this.vchXMLErrorField = value;
                    this.RaisePropertyChanged("vchXMLError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ComunService.IComunContract")]
    public interface IComunContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComunContract/setLogError", ReplyAction="http://tempuri.org/IComunContract/setLogErrorResponse")]
        void setLogError(PLD.Web.ComunService.LogError error);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComunContract/setLogError", ReplyAction="http://tempuri.org/IComunContract/setLogErrorResponse")]
        System.Threading.Tasks.Task setLogErrorAsync(PLD.Web.ComunService.LogError error);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComunContract/setCargaInformacion", ReplyAction="http://tempuri.org/IComunContract/setCargaInformacionResponse")]
        PLD.Web.ComunService.ServiceResult setCargaInformacion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComunContract/setCargaInformacion", ReplyAction="http://tempuri.org/IComunContract/setCargaInformacionResponse")]
        System.Threading.Tasks.Task<PLD.Web.ComunService.ServiceResult> setCargaInformacionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComunContract/getBitacoraCarga", ReplyAction="http://tempuri.org/IComunContract/getBitacoraCargaResponse")]
        PLD.Web.ComunService.Carga[] getBitacoraCarga(System.DateTime dttFechIni, System.DateTime dttFechFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComunContract/getBitacoraCarga", ReplyAction="http://tempuri.org/IComunContract/getBitacoraCargaResponse")]
        System.Threading.Tasks.Task<PLD.Web.ComunService.Carga[]> getBitacoraCargaAsync(System.DateTime dttFechIni, System.DateTime dttFechFin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IComunContractChannel : PLD.Web.ComunService.IComunContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComunContractClient : System.ServiceModel.ClientBase<PLD.Web.ComunService.IComunContract>, PLD.Web.ComunService.IComunContract {
        
        public ComunContractClient() {
        }
        
        public ComunContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComunContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComunContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComunContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void setLogError(PLD.Web.ComunService.LogError error) {
            base.Channel.setLogError(error);
        }
        
        public System.Threading.Tasks.Task setLogErrorAsync(PLD.Web.ComunService.LogError error) {
            return base.Channel.setLogErrorAsync(error);
        }
        
        public PLD.Web.ComunService.ServiceResult setCargaInformacion() {
            return base.Channel.setCargaInformacion();
        }
        
        public System.Threading.Tasks.Task<PLD.Web.ComunService.ServiceResult> setCargaInformacionAsync() {
            return base.Channel.setCargaInformacionAsync();
        }
        
        public PLD.Web.ComunService.Carga[] getBitacoraCarga(System.DateTime dttFechIni, System.DateTime dttFechFin) {
            return base.Channel.getBitacoraCarga(dttFechIni, dttFechFin);
        }
        
        public System.Threading.Tasks.Task<PLD.Web.ComunService.Carga[]> getBitacoraCargaAsync(System.DateTime dttFechIni, System.DateTime dttFechFin) {
            return base.Channel.getBitacoraCargaAsync(dttFechIni, dttFechFin);
        }
    }
}
